//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Code generated by openapi-gen. DO NOT EDIT.

// This file was autogenerated by openapi-gen. Do not edit it manually!

package v1alpha1

import (
	common "k8s.io/kube-openapi/pkg/common"
	spec "k8s.io/kube-openapi/pkg/validation/spec"
)

func GetOpenAPIDefinitions(ref common.ReferenceCallback) map[string]common.OpenAPIDefinition {
	return map[string]common.OpenAPIDefinition{
		"github.com/openshift/splunk-token-operator/api/v1alpha1.SplunkToken":       schema_openshift_splunk_token_operator_api_v1alpha1_SplunkToken(ref),
		"github.com/openshift/splunk-token-operator/api/v1alpha1.SplunkTokenSpec":   schema_openshift_splunk_token_operator_api_v1alpha1_SplunkTokenSpec(ref),
		"github.com/openshift/splunk-token-operator/api/v1alpha1.SplunkTokenStatus": schema_openshift_splunk_token_operator_api_v1alpha1_SplunkTokenStatus(ref),
	}
}

func schema_openshift_splunk_token_operator_api_v1alpha1_SplunkToken(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "SplunkToken is the Schema for the splunktokens API.",
				Type:        []string{"object"},
				Properties: map[string]spec.Schema{
					"kind": {
						SchemaProps: spec.SchemaProps{
							Description: "Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"apiVersion": {
						SchemaProps: spec.SchemaProps{
							Description: "APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"metadata": {
						SchemaProps: spec.SchemaProps{
							Default: map[string]interface{}{},
							Ref:     ref("k8s.io/apimachinery/pkg/apis/meta/v1.ObjectMeta"),
						},
					},
					"spec": {
						SchemaProps: spec.SchemaProps{
							Default: map[string]interface{}{},
							Ref:     ref("github.com/openshift/splunk-token-operator/api/v1alpha1.SplunkTokenSpec"),
						},
					},
					"status": {
						SchemaProps: spec.SchemaProps{
							Default: map[string]interface{}{},
							Ref:     ref("github.com/openshift/splunk-token-operator/api/v1alpha1.SplunkTokenStatus"),
						},
					},
				},
			},
		},
		Dependencies: []string{
			"github.com/openshift/splunk-token-operator/api/v1alpha1.SplunkTokenSpec", "github.com/openshift/splunk-token-operator/api/v1alpha1.SplunkTokenStatus", "k8s.io/apimachinery/pkg/apis/meta/v1.ObjectMeta"},
	}
}

func schema_openshift_splunk_token_operator_api_v1alpha1_SplunkTokenSpec(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "SplunkTokenSpec defines the desired state of SplunkToken.",
				Type:        []string{"object"},
				Properties: map[string]spec.Schema{
					"tokenName": {
						SchemaProps: spec.SchemaProps{
							Description: "TokenName is the name of the cluster's HTTP Event Collector token on the Splunk instance.",
							Type:        []string{"string"},
							Format:      "",
						},
					},
				},
			},
		},
	}
}

func schema_openshift_splunk_token_operator_api_v1alpha1_SplunkTokenStatus(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "SplunkTokenStatus defines the observed state of SplunkToken.",
				Type:        []string{"object"},
			},
		},
	}
}
