//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Code generated by openapi-gen. DO NOT EDIT.

// This file was autogenerated by openapi-gen. Do not edit it manually!

package v1alpha1

import (
	common "k8s.io/kube-openapi/pkg/common"
	spec "k8s.io/kube-openapi/pkg/validation/spec"
)

func GetOpenAPIDefinitions(ref common.ReferenceCallback) map[string]common.OpenAPIDefinition {
	return map[string]common.OpenAPIDefinition{
		"./api/v1alpha1.SplunkToken":       schema__api_v1alpha1_SplunkToken(ref),
		"./api/v1alpha1.SplunkTokenSpec":   schema__api_v1alpha1_SplunkTokenSpec(ref),
		"./api/v1alpha1.SplunkTokenStatus": schema__api_v1alpha1_SplunkTokenStatus(ref),
	}
}

func schema__api_v1alpha1_SplunkToken(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "SplunkToken is the Schema for the splunktokens API.",
				Type:        []string{"object"},
				Properties: map[string]spec.Schema{
					"kind": {
						SchemaProps: spec.SchemaProps{
							Description: "Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"apiVersion": {
						SchemaProps: spec.SchemaProps{
							Description: "APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"metadata": {
						SchemaProps: spec.SchemaProps{
							Default: map[string]interface{}{},
							Ref:     ref("k8s.io/apimachinery/pkg/apis/meta/v1.ObjectMeta"),
						},
					},
					"spec": {
						SchemaProps: spec.SchemaProps{
							Default: map[string]interface{}{},
							Ref:     ref("./api/v1alpha1.SplunkTokenSpec"),
						},
					},
					"status": {
						SchemaProps: spec.SchemaProps{
							Default: map[string]interface{}{},
							Ref:     ref("./api/v1alpha1.SplunkTokenStatus"),
						},
					},
				},
			},
		},
		Dependencies: []string{
			"./api/v1alpha1.SplunkTokenSpec", "./api/v1alpha1.SplunkTokenStatus", "k8s.io/apimachinery/pkg/apis/meta/v1.ObjectMeta"},
	}
}

func schema__api_v1alpha1_SplunkTokenSpec(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "SplunkTokenSpec defines the desired state of SplunkToken.",
				Type:        []string{"object"},
				Properties: map[string]spec.Schema{
					"name": {
						SchemaProps: spec.SchemaProps{
							Description: "Name is the name of the cluster's HTTP Event Collector token on the Splunk instance.",
							Default:     "",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"defaultIndex": {
						SchemaProps: spec.SchemaProps{
							Description: "DefaultIndex is the default Splunk index that logs are sent to.",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"allowedIndexes": {
						SchemaProps: spec.SchemaProps{
							Description: "AllowedIndexes is a list of other indexes that this token is allowed to send logs to.",
							Type:        []string{"array"},
							Items: &spec.SchemaOrArray{
								Schema: &spec.Schema{
									SchemaProps: spec.SchemaProps{
										Default: "",
										Type:    []string{"string"},
										Format:  "",
									},
								},
							},
						},
					},
				},
				Required: []string{"name"},
			},
		},
	}
}

func schema__api_v1alpha1_SplunkTokenStatus(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "SplunkTokenStatus defines the observed state of SplunkToken.",
				Type:        []string{"object"},
			},
		},
	}
}
